name: Build
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - '**/*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    outputs:
      branch_name: ${{ steps.build.outputs.branch }}
      app_version: ${{ steps.build.outputs.app_version }}
    env:
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        id: build
        run: |
          export APP_VERSION=$(cat gradle.properties | grep -e '^version=' | cut -d'=' -f 2)
          export BRANCH_VERSION=$(echo ${GITHUB_REF#refs/heads/})
          export BRANCH_VERSION=$(echo ${BRANCH_VERSION#refs/tags/})
          echo "app_version=$APP_VERSION" >> $GITHUB_OUTPUT
          echo "branch=$BRANCH_VERSION" >> $GITHUB_OUTPUT
          echo "DEBUG: $GITHUB_OUTPUT"
          ./gradlew build

      - name: Publish Artifacts
        id: publish
        run: |
          ./gradlew publish
